manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: vendelieu
      url-base: https://github.com/vendelieu
  projects:
    - name: zmk-config
      remote: vendelieu
      revision: main
      import: app/west.yml
  self:
    path: config
